Controllers/ArticleController.cs
using AccountManagement.Data;
using AccountManagement.Models;
using AccountManagement.Models.Articles;
using AccountManagement.Models.Rating;
using AccountManagement.Models.Trains;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace AccountManagement.Controllers
{
	public class ArticleController : Controller
	{
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        public ArticleController(ApplicationDbContext db, UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }
        public IActionResult Index()
		{
            var articles = _db.Articles.ToList();
			return View(articles);
		}
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(CreateArticleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var article = new Article
                {
                    Id = model.Id,
                    TimeItWasAdded = DateTime.Now,
                    Content = model.Content,
                    Title = model.Title
                };
                _db.Articles.Add(article);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var theArticle = _db.Articles.FirstOrDefault(a => a.Id == id);
            var article = new EditArticleViewModel
            {
                Id = theArticle.Id,
                TimeItWasAdded = theArticle.TimeItWasAdded,
                Content = theArticle.Content,
                Title = theArticle.Title
            };

            return View(article);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditArticleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var article = _db.Articles.FirstOrDefault(a => a.Id == id);

                article.Id = model.Id;
                article.TimeItWasAdded = model.TimeItWasAdded;
                article.Content = model.Content;
                article.Title = model.Title;
                article.TimeItWasAdded = DateTime.Now;
                _db.Articles.Update(article);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var theArticle = _db.Articles.FirstOrDefault(a => a.Id == id);
            var article = new DeleteArticleViewModel
            {
                Id = theArticle.Id,
                Title = theArticle.Title,
                Content = theArticle.Content,
            };

            return View(article);
        }
        [Authorize(Roles ="Admin")]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var article = _db.Articles.FirstOrDefault(a => a.Id == id);
            if (article != null)
            {
                _db.Articles.Remove(article);
                await _db.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class ContactsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/TrainController.cs
using AccountManagement.Data;
using Humanizer.Localisation;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using AccountManagement.Models.Trains;
using AccountManagement.Models;
using Microsoft.AspNetCore.Authorization;
using AccountManagement.Models.Rating;
using Microsoft.AspNetCore.Identity;

namespace AccountManagement.Controllers
{
    public class TrainController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        public TrainController(ApplicationDbContext db,UserManager<ApplicationUser> userManager) 
        {
            _db = db; 
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var trains = _db.Trains.Include(a => a.TypeOfTrain).Include(a => a.Schedules).ToList();
            if (trains.Count!= 0)
            {
                foreach (var train in trains)
                {
                    if (train.Schedules.Count()!=0)
                    {
                        foreach (var trainSchedule in train.Schedules)
                        {
                            if ((DateTime.Compare(DateTime.Now, trainSchedule.StartsAtStation) == 0 || DateTime.Compare(DateTime.Now, trainSchedule.StartsAtStation) > 0) && DateTime.Compare(DateTime.Now, trainSchedule.ArrivesAtDestination) < 0)
                            {
                                train.IsItBusy = true;
                            }
                            else
                            {
                                train.IsItBusy = false;
                            }
                        }
                    }
                    
                }
            }
            return View(trains);
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            ViewData["TypeOfTrainId"] = new SelectList(_db.TypeOfTrains, "Id", "Name");
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(CreateTrainViewModel model)
        {
            if (ModelState.IsValid)
            {
                foreach (var item in _db.Trains)
                {
                    if(item.SerialNumber == model.SerialNumber)
                    {
                        ViewBag.SerialNumber = "Влак с този сериен номер вече съществува";
                        ViewBag.CategoryId = new SelectList(_db.TypeOfTrains, "Id", "Name", model.TypeOfTrainId);
                        return View(model);
                    }
                }
                var train = new Train
                {
                    Id = model.Id,
                    SerialNumber = model.SerialNumber,
                    Line = model.Line,
                    TypeOfTrainId = model.TypeOfTrainId,
                    AmountOfPassagers = model.AmountOfPassagers
                };
                _db.Trains.Add(train);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.CategoryId = new SelectList(_db.TypeOfTrains, "Id", "Name", model.TypeOfTrainId);
            return View(model);
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewData["TypeOfTrainId"] = new SelectList(_db.TypeOfTrains, "Id", "Name");
            var theTrain = _db.Trains.FirstOrDefault(a => a.Id == id);
            var train = new EditTrainViewModel
            {
                Id = theTrain.Id,
                SerialNumber = theTrain.SerialNumber,
                Line = theTrain.Line,
                TypeOfTrainId = theTrain.TypeOfTrainId,
                AmountOfPassagers = theTrain.AmountOfPassagers
            };

            return View(train);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditTrainViewModel model)
        {
            if (ModelState.IsValid)
            {
                var train = _db.Trains.FirstOrDefault(a => a.Id == id);

                foreach (var item in _db.Trains)
                {
                    if (item.SerialNumber == model.SerialNumber)
                    {
                        ViewBag.SerialNumber = "Влак с този сериен номер вече съществува";
                        ViewBag.CategoryId = new SelectList(_db.TypeOfTrains, "Id", "Name", model.TypeOfTrainId);
                        return View(model);
                    }
                }

                train.Id = model.Id;
                train.Line = model.Line;
                train.SerialNumber = model.SerialNumber;
                train.TypeOfTrainId = model.TypeOfTrainId;
                train.AmountOfPassagers = model.AmountOfPassagers;
                _db.Trains.Update(train);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.TypeOfTrainId = new SelectList(_db.TypeOfTrains, "Id", "Name", model.TypeOfTrainId);
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Delete(int id)
        {

            var theTrain = _db.Trains.FirstOrDefault(a => a.Id == id);
            ViewBag.ChosenTypeOfTrain = _db.TypeOfTrains.Where(a => a.Id == theTrain.TypeOfTrainId);
            var train = new DeleteTrainViewModel
            {
                Id = theTrain.Id,
                Line = theTrain.Line,
                TypeOfTrainId = theTrain.TypeOfTrainId,
                SerialNumber = theTrain.SerialNumber,
                AmountOfPassagers = theTrain.AmountOfPassagers
            };
            return View(train);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var train = _db.Trains.FirstOrDefault(a => a.Id == id);
            if (train != null)
            {
                _db.Trains.Remove(train);
                await _db.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
        [Authorize]
        [HttpGet]
        public IActionResult Rate(int id)
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public IActionResult Rate(int id,CreateRatingViewModel model)
        {
            if (ModelState.IsValid)
            {
                var rating = new Assesment
                {
                    RatingScore = model.RatingScore,
                    Comment = model.Comment,
                    TrainId = id,
                    UserId = _userManager.GetUserId(User),
                    TimeItWasAdded = DateTime.Now
                };
                _db.Ratings.Add(rating);
                _db.SaveChanges();

                decimal ratingScoreSum = 0;
                var ratings = _db.Ratings.Where(a => a.TrainId == id);
                foreach (var rate in ratings)
                {
                    ratingScoreSum += rate.RatingScore;
                }
                decimal ratingScore = Math.Round((ratingScoreSum/ratings.Count()),1);
                var train = _db.Trains.FirstOrDefault(a => a.Id == id);
                train.RatingScore = $"{ratingScore}";
                _db.Trains.Update(train);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AccountManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-blue border-bottom box-shadow mb-3 design">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color:white">ВДЖ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Train" asp-action="Index">Влакове</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Schedule" asp-action="Index">Маршрути</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Contacts" asp-action="Index">Контакти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Information" asp-action="Index">Информация</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Article" asp-action="Index">Новини</a>
                        </li>
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <style>
        .design {
            background-color: darkred;
        }
    </style>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>